# Generated by Django 4.2.5 on 2023-09-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeServer', '0003_remove_servicecategory_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='homeServer.servicecategory'),
        ),
    ]
