# Generated by Django 4.2.5 on 2023-09-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeServer', '0004_alter_service_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='service_date',
            new_name='service_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_duration',
        ),
    ]
